package com.accenture.sme_planner.enums;

public enum ActivityType {
    LATERAL_CALENDAR_TRAINING_FULL_DAY,
    BLENDED_LEARNING,
    LATERAL_CALENDAR_TRAINING_HALF_DAY,
    ADHOC_TRAINING,
    CONTENT_DEVELOPMENT,
    PUBLIC_HOLIDAY,
    LEAVE,
    BYTE_SIZED,
    EVALUATION,
    SKILL_UPGRADE,
    PROGRAM_AND_SESSION_PLANNING,
    OTHERS
}
